name: "Build"

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: wtfjoke/setup-node@addCacheHitOutPut
        id: cache
        with:
          node-version: "14"
          cache: "yarn"
      - run: yarn install
        if: steps.cache.outputs.cache-hit != 'true'
      - run: echo "cache hit ${{ steps.cache.outputs.cache-hit }}"
